### PR TITLE
Amd

### PR DESCRIPTION
**Pull request by mogstad**

### CODE REVIEW

**Comment by Rosey** [comment]
LGTM!

When I tried to get this running on my new MBP it kept giving me errors but it works fine on my personal MBP that was already set up. Not sure if there's just a command I was missing, I assume it's on my end and not on wysiwyg's end.

**Comment by Rosey** [comment]
(at any rate, updating the readme could help with that!)

**Comment by mogstad** [comment]
Yeah, will create a task to update the readme. `npm install` should be enough to get up and running. I ran  it on an empty slate yesterday and it managed to compile fine.

**Comment by Rosey** [comment]
hm weird, definitely did that and hit a wall but I don't have that computer with me atm so I can't say exactly what happened.

**Pull request merged**
